import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/Landing';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Green Gannet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Landing />
      </main>

      <footer></footer>
    </div>
  );
}
